Fix name string representation
string.join expects strings, not StringElement:

openprovider.py/openprovider/models.pyc in __str__(self)
    114     def __str__(self):
    115         if hasattr(self, "prefix"):
--> 116             return " ".join((self.first_name, self.prefix, self.last_name))
    117         else:
    118             return " ".join((self.first_name, self.last_name))

TypeError: sequence item 0: expected string, lxml.objectify.StringElement found